---
- hosts: all
  remote_user: vagrant
  tasks:
  - name: Installing java
    yum: name=java state=present
  - name: Installing git
    yum: name=git-core state=present
  - name: Installing Jenkins
    yum: name=jenkins state=present
